export enum ERROR_NAMES {
  NOT_FOUND = "NOT_FOUND",
  SOMETHING_WRONG = "SOMETHING_WENT_WRONG",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORISED = 'UNAUTHORISED'
}

export enum HTTP_CODES {
  NOT_FOUND = 404,
  SOMETHING_WRONG = 500,
  BAD_REQUEST = 400,
  UNAUTHORISED = 401
}
